---
name: wut
services:
  web:
    command: deno run --allow-all --watch src/srv.ts
    # command: -f /dev/null
    # entrypoint: /usr/bin/tail
    # tty: true
    environment:
      - PORT=9000
    hostname: wut-srv
    image: docker.io/denoland/deno:latest
    ports:
      - "9000:9000/tcp"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /vol/src/code/meop/wut
        target: /wut
      - type: bind
        source: /vol/src/code/meop/wut-config
        target: /wut-config
    working_dir: /wut
