---
name: wut
services:
  srv:
    command: deno run --allow-all --env-file --watch src/srv.ts
    # command: -f /dev/null
    # entrypoint: /usr/bin/tail
    # tty: true
    env_file:
      - path: '../.env'
        required: true
    environment:
      - PORT=9000
    hostname: wut-srv
    image: docker.io/denoland/deno:latest
    ports:
      - '9000:9000/tcp'
    restart: unless-stopped
    volumes:
      - type: bind
        source: '..'
        target: /wut
      - type: bind
        source: '../../wut-config'
        target: /wut-config
      - type: bind
        source: '../../wut-config-secret'
        target: /wut-config-secret
    working_dir: /wut
