---
name: wut
services:
  web:
    command: deno run --allow-all --env-file --watch src/srv.ts
    # command: -f /dev/null
    # entrypoint: /usr/bin/tail
    # tty: true
    env_file:
      - path: '../.env'
        required: true
    hostname: wut-web
    image: docker.io/denoland/deno:latest
    ports:
      - '9000:80/tcp'
    restart: unless-stopped
    volumes:
      - type: bind
        source: '../../../shire'
        target: /shire
      - type: bind
        source: '../../wut'
        target: /@wut/wut
      - type: bind
        source: '../../wut-config'
        target: /@wut/wut-config
      - type: bind
        source: '../../wut-config-secret'
        target: /@wut/wut-config-secret
    working_dir: /@wut/wut
